version: '3'

services:
  db:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: market
      POSTGRES_USER: market
      POSTGRES_PASSWORD: market
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
